name: flutter_theprojectname_test
description: A new Flutter project.
version: 1.0.0+1
homepage:
repository:
publish_to: "none"

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  theprojectname:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
